## Torch

### Torch.topk

同tensor.topk

<u>torch.topk(input, k, dim=None, largest=True, sorted=True, *, out=None)<u>

Returns the k largest elements of the given input tensor along **a given dimension**. 维数不会变化，但是dim维维度减为k

If **dim is not given**, the **last dimension** of the input is chosen.

If largest is False then the k smallest elements are returned.

A namedtuple of (values, indices) is returned, where the indices are the indices of the elements in the original input tensor.

The boolean option sorted if True, will make sure that the returned k elements are themselves sorted

### Torch.flatten

<u>torch.flatten(input, start_dim=0, end_dim=- 1) → Tensor<u>

Flattens input by reshaping it into a one-dimensional tensor. If **start_dim** or **end_dim** are passed, only dimensions starting with **start_dim** and ending with **end_dim** are flattened. The order of elements in input is unchanged.

Unlike NumPy’s flatten, which always copies input’s data, this function may return the original object, a view, or copy. If no dimensions are flattened, then the original object input is returned. Otherwise, if input can be viewed as the flattened shape, then that view is returned. Finally, only if the input cannot be viewed as the flattened shape is input’s data copied. See torch.Tensor.view() for details on when a view will be returned.

NOTE

<font color=red>Flattening a zero-dimensional tensor will return a one-dimensional view.</font>

### Torch.arange
<u>torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor<u>
    
跟python里面的range()一样

### Torch.gather

<u>torch.gather(input, dim, index, *, sparse_grad=False, out=None) → Tensor<u>

Gathers values along an axis specified by dim.

For a 3-D tensor the output is specified by:

out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
    
out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1

out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2

input and index must have the same number of dimensions. It is also required that index.size(d) <= input.size(d) 
                                                                                                               
for all dimensions d != dim. out will have the same shape as index. Note that input and index do not broadcast against each other.

Parameters
                                                                                                               input (Tensor) – the source tensor

dim (int) – the axis along which to index

index (LongTensor) – the indices of elements to gather

gather是从input里面取数，scatter是将src的数填入到self中，他们都有index。
gather的输出比input少一维，少的就是dim这一维

### Torch.gt

<u>torch.gt(input, other, *, out=None) → Tensor<u>

Computes **input > other** element-wise.(gt=greater than)

The second argument can be a number or a tensor whose shape is **broadcastable** with the first argument.

Parameters
    
input (Tensor) – the tensor to compare

other (Tensor or float) – the tensor or value to compare

Returns
A boolean tensor that is True where input is greater than other and False elsewhere

Example:

>torch.gt(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))
    
>tensor([[False, True], [False, False]])

### Torch.where

<u>torch.where(condition, x, y) → Tensor<u>

Return a tensor of elements selected from either x or y, depending on condition.

if condition_i:output_i=x_i;
else output_i=y_i


### Torch.var

<u>torch.var(input, dim, unbiased, keepdim=False, *, out=None) → Tensor<u>
    
计算方差
    
If unbiased is True, Bessel’s correction will be used. Otherwise, the sample variance is calculated, without any correction.

Parameters
    
input (Tensor) – the input tensor.

dim (int or tuple of python:ints) – the dimension or dimensions to reduce.

Keyword Arguments
    
unbiased (bool) – whether to use Bessel’s correction (\delta N = 1δN=1).

keepdim (bool) – whether the output tensor has dim retained or not.

out (Tensor, optional) – the output tensor.

<u>torch.var(input, unbiased) → Tensor<u>

### Torch.nonzero
<u>torch.nonzero(input, *, out=None, as_tuple=False) → LongTensor or tuple of LongTensors<u>

返回input中所有不为0的值的坐标。
as_tuple=false时，返回一个二维矩阵，0维的维度是input中非0值的个数，1维的维度是input的维数（坐标）。
as_tuple=true时，返回一个tensor的tuple，tuple[i]表示input中所有非0值第i维的坐标。
    
> torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))
    
> tensor([[ 0],
        [ 1],
        [ 2],
        [ 4]])
  
> torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                              [0.0, 0.4, 0.0, 0.0],
                              [0.0, 0.0, 1.2, 0.0],
                              [0.0, 0.0, 0.0,-0.4]]))
    
> tensor([[ 0,  0],
         [ 1,  1],
         [ 2,  2],
         [ 3,  3]])
  
> torch.nonzero(torch.tensor([1, 1, 1, 0, 1]), as_tuple=True)

>(tensor([0, 1, 2, 4]),)
  
> torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                              [0.0, 0.4, 0.0, 0.0],
                              [0.0, 0.0, 1.2, 0.0],
                              [0.0, 0.0, 0.0,-0.4]]), as_tuple=True) 
    
>(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

### Torch.count_nonzero

<u>torch.count_nonzero(input, dim=None) → Tensor<u>
    
Counts the number of non-zero values in the tensor input along the given dim. If no dim is specified then all non-zeros in the tensor are counted.

Parameters
    
input (Tensor) – the input tensor.

dim (int or tuple of python:ints, optional) – Dim or tuple of dims along which to count non-zeros.



### Torch.squeeze

<u>torch.squeeze(input, dim=None, *, out=None) → Tensor<u>

dim维度为1的时候，删除这一维度
    
unsqueeze就是加上一维维度为1的

### Torch.split

<u>torch.split(tensor, split_size_or_sections, dim=0)<u>
    
Splits the tensor into chunks. Each chunk is a view of the original tensor.

If split_size_or_sections is an integer type, then tensor will be split into equally sized chunks (if possible). Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by split_size.

If split_size_or_sections is a list, then tensor will be split into len(split_size_or_sections) chunks with sizes in dim according to split_size_or_sections.(split_size_or_sections.sum()=tensor.shape[dim])

> a=tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
    
> torch.split(a, 2)
    
> (tensor([[0, 1],
           [2, 3]]),
   tensor([[4, 5],
           [6, 7]]),
   tensor([[8, 9]]))

> torch.split(a, [1,4])
    
> (tensor([[0, 1]]),
   tensor([[2, 3],
           [4, 5],
           [6, 7],
           [8, 9]]))


###  Torch.sort

<u>torch.sort(input, dim=- 1, descending=False, stable=False, *, out=None)<u>
    
Sorts the elements of the input tensor along a given dimension in ascending order by value.

If **dim** is not given, the last dimension of the input is chosen.

If **descending** is True then the elements are sorted in descending order by value.

If **stable** is True then the sorting routine becomes stable, preserving the order of equivalent elements.

A namedtuple of (values, indices) is returned, where the values are the sorted values and indices are the indices of the elements in the original input tensor.

设定的dim就是所有值在这一维上排序，与其他维无关。默认是最后一维。返回排好序的tensor，以及对应的坐标。

>a=torch.tensor([[8,2],
                 [3,7]])
>a.sort(0)
>values=tensor([3,2],
               [8,7])
>index=tensor([1,0],
              [0,1])

### Torch.narrow

<u>torch.narrow(input, dim, start, length) → Tensor<u>
    
Returns a new tensor that is a narrowed version of input tensor. The dimension dim is input from start to start + length. The returned tensor and input tensor share the same underlying storage.

Parameters
    
input (Tensor) – the tensor to narrow

dim (int) – the dimension along which to narrow

start (int) – the starting dimension

length (int) – the distance to the ending dimension

参数里是length，不是end


### Torch.mul
<u>torch.mul(input, other, *, out=None) → Tensor<u>

对位相乘，等同于*

### Torch.norm
<u>torch.norm(input, p='fro', dim=None, keepdim=False, out=None, dtype=None)<u>

计算正则化，p=2的时候相当于计算模长

### Torch.mm
<u>torch.mm(input, mat2, *, out=None) → Tensor<u>

矩阵乘法

### Torch.enisum
<u>torch.einsum(equation, *operands) → Tensor<u>

多维向量下的矩阵乘法,实现对应维度相乘。<br>
可以用...代替不需要的维度。<br>
eqution不规整的时候，自动permute，所以不需要手动permute。<br>

In [1]:
import torch

a = torch.randn(2, 3, 4)
b = torch.randn(2, 4, 5)
c = torch.einsum('bmd,bdn->bmn', a, b)
print(c)

tensor([[[ 1.4281, -3.1645, -3.6999,  2.1394, -0.4215],
         [ 0.6402,  4.1123,  2.9571, -0.7685,  2.9256],
         [ 2.8164, -3.6105, -1.8588,  1.4229, -0.1947]],

        [[ 2.9542,  1.8481,  0.1283,  0.6328,  0.6846],
         [-0.5328, -0.9790,  0.9083, -2.4849, -1.6972],
         [ 8.4342,  0.2057,  4.2363, -2.3439,  0.2636]]])


In [3]:
a = torch.randn(2, 2, 3, 4)
b = torch.randn(2, 4, 5)
c = torch.einsum('...md,...dn->...mn', a, b)
print(c)

tensor([[[[ 1.3726,  2.5198, -1.5947, -2.2563, -0.4961],
          [-0.2153,  2.2099, -0.0079, -2.7648,  1.8108],
          [-1.2267,  0.3540,  1.0429, -0.9195,  1.7760]],

         [[ 1.1354, -0.4151,  0.2485,  1.2071, -0.6641],
          [-0.4179,  0.6905, -2.2383, -1.2972,  0.1543],
          [-1.7031, -0.0978,  0.2102,  1.2359, -1.5874]]],


        [[[ 1.3569, -0.4120,  0.6817,  3.4328,  0.3849],
          [ 4.1589,  1.8688, -1.8636, -1.4751,  1.0052],
          [ 1.8234, -0.1228, -1.3089, -1.1607, -0.3277]],

         [[-0.9255,  0.5298, -2.7719,  1.1705, -3.2185],
          [ 0.0174,  0.3291, -0.6998, -0.6752,  0.0729],
          [ 0.3122, -0.1513,  0.5505, -0.8678,  1.8534]]]])


## Torch.Tensor

### Torch.Tensor.scatter_

<u>Tensor.scatter_(dim, index, src, reduce=None) → Tensor<u>

与Tensor.Tensor.scatter相同

Writes all values from the tensor **src** into **self** at the indices specified in the **index** tensor. 

对于所有src中的值src[i][j][k]坐标为(i,j,k)，将dim维替换成index[i][j][k],假设dim=2，得到新坐标(i,index[i][j][k],k)；在self中新坐标位置，也就是self[i][index[i][j][k]][k]位置填入src[i][j][k].

所以shape(index)=shape(src),一一对应；
max(index)<=self.shape[dim],替换的坐标不能超过这一维的维度

scatter可用于构建onehot函数；与topk可能经常配套使用，因为topk返回前k个值和坐标，可以通过scatter构建只有topk有权值，其他地方为0的权值矩阵

### Torch.Tensor.index_add_

<u>Tensor.index_add_(dim, index, tensor, *, alpha=1) → Tensor<u>

指定tensor行或列的内容与self相加.
index.shape[dim]=tensor[dim].
dim=0时，self[index[i]]+=tensor[i]

Accumulate the elements of **alpha** times **tensor** into the **self tensor** by adding to the indices in the order given in **index**. 

For example, if dim == 0, index[i] == j, and alpha=-1, then the ith row of tensor is subtracted from the jth row of self.

The dim_th dimension of tensor must have the same size as the length of index (which must be a vector), and all other dimensions must match self, or an error will be raised.

Parameters

dim (int) – dimension along which to index

index (IntTensor or LongTensor) – indices of tensor to select from

tensor (Tensor) – the tensor containing values to add

Keyword Arguments

alpha (Number) – the scalar multiplier for tensor

In [9]:
import torch
a=torch.ones(3,5)
index=torch.tensor([0,2,4,1])
b=torch.tensor(range(1,13)).reshape(3,4).float()
print("a=",a)
print("b=",b)
c=a.index_add_(1,index,b,alpha=2)
print("c=",c)

a= tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
b= tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
c= tensor([[ 3.,  9.,  5.,  1.,  7.],
        [11., 17., 13.,  1., 15.],
        [19., 25., 21.,  1., 23.]])


### Torch.Tensor.expand
<u>Tensor.expand(*sizes) → Tensor<u>
将tensor按照*sizes进行广播，如果是在开头拓维度是可以的，在中间或者后面拓维度要先unsqueeze

In [2]:
import torch

a = torch.randn(3, 4)
b = a.expand(3, 3, 4)
print("a=", a)
print("b=", b)
c = a.expand(3, 4, 3)


a= tensor([[ 0.9780,  0.0358, -1.1768, -0.0389],
        [ 0.3494, -0.9509, -0.0652,  1.5835],
        [-0.7072,  1.6012, -1.4796,  0.9156]])
b= tensor([[[ 0.9780,  0.0358, -1.1768, -0.0389],
         [ 0.3494, -0.9509, -0.0652,  1.5835],
         [-0.7072,  1.6012, -1.4796,  0.9156]],

        [[ 0.9780,  0.0358, -1.1768, -0.0389],
         [ 0.3494, -0.9509, -0.0652,  1.5835],
         [-0.7072,  1.6012, -1.4796,  0.9156]],

        [[ 0.9780,  0.0358, -1.1768, -0.0389],
         [ 0.3494, -0.9509, -0.0652,  1.5835],
         [-0.7072,  1.6012, -1.4796,  0.9156]]])


RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 2.  Target sizes: [3, 4, 3].  Tensor sizes: [3, 4]

In [3]:
c = a.unsqueeze(-1).expand(3, 4, 3)
print(c)

tensor([[[ 0.9780,  0.9780,  0.9780],
         [ 0.0358,  0.0358,  0.0358],
         [-1.1768, -1.1768, -1.1768],
         [-0.0389, -0.0389, -0.0389]],

        [[ 0.3494,  0.3494,  0.3494],
         [-0.9509, -0.9509, -0.9509],
         [-0.0652, -0.0652, -0.0652],
         [ 1.5835,  1.5835,  1.5835]],

        [[-0.7072, -0.7072, -0.7072],
         [ 1.6012,  1.6012,  1.6012],
         [-1.4796, -1.4796, -1.4796],
         [ 0.9156,  0.9156,  0.9156]]])


## Torch.nn.funcational

### Torch.nn.funcational.cosine_similarity
<u>torch.nn.functional.cosine_similarity(x1, x2, dim=1, eps=1e-8) → Tensor<u>
计算x1与x2的余弦相似度